version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Senha1234
      POSTGRES_DB: N_Bank_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  flask_app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - postgres
    networks:
      - nbank_network
    restart: always

volumes:
  postgres_data:

networks:
  nbank_network:
    driver: bridge